name: 'Terraform'
on: [pull_request]

permissions:
  pull-requests: write
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Infracost
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -out tfplan.binary

    - name: Terraform Show
      working-directory: ./terraform
      run: terraform show -json tfplan.binary > plan.json

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -input=false -auto-approve

    - name: Generate Infracost JSON
      run: infracost breakdown --path plan.json --format json --out-file /tmp/infracost.json
      working-directory: ./terraform

    - name: Post Infracost comment
      run: |
        infracost comment github --path /tmp/infracost.json \
                                   --repo $GITHUB_REPOSITORY \
                                   --github-token ${{github.token}} \
                                   --pull-request ${{github.event.pull_request.number}} \
                                   --behavior update
